version: '3.8'

services:
  backend:
    container_name: bookmytrip_backend
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/bookmytrip
      - EXTERNAL_CAB_API_URL=https://cc-cab-miniproject-964317129318.asia-south1.run.app
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - bookmytrip-network

  mongo:
    container_name: bookmytrip_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - bookmytrip-network

networks:
  bookmytrip-network:
    driver: bridge

volumes:
  mongo_data: